# All configurations and dependency files

'Configuration':
  - tsconfig.json
  - tsconfig.*.json
  - jest.json
  - jest.*.json
  - nx.json
  - workspace.json
  - workspace.*.json
  - migrations.json
  - next.config.js
  - nextjs-base.config.*
  - firebase.json
  - firebase.indexes.json
  - firebase.rules
  - babel.config.js
  - .babelrc
'Dependencies':
  - package.json
  - package-lock.json
  - yarn.lock
'TypeScript':
  - tsconfig.json
  - tsconfig.*.json
'Jest':
  - jest.json
  - jest.*.json
'Nx':
  - nx.json
  - workspace.json
  - workspace.*.json
  - migrations.json
'Nextjs':
  - next.config.js
  - nextjs-base.config.*
'Firebase':
  - firebase.json
  - firebase.indexes.json
  - firebase.rules
  - .firebaserc
'Babel':
  - babel.config.js
  - .babelrc

# Monorepo Top Level

'Mono App':
  - apps/*
  - apps/**/*
'Mono Lib':
  - libs/*
  - libs/**/*
'Mono Shared':
  - libs/shared/*
  - libs/shared/**/*

# Monorepo Apps

'App: www':
  - apps/www/*
  - apps/www/**/*
'App: console':
  - apps/console/*
  - apps/console/**/*

# Aglyn SDK

'ADK Core':
  - libs/core/data/framework/*
  - libs/core/data/framework/**/*
'ADK Renderer':
  - libs/core/feature/renderer/*
  - libs/core/feature/renderer/**/*
'ADK Besigner':
  - libs/core/feature/besigner/*
  - libs/core/feature/besigner/**/*
'ADK Add-ons':
  - libs/addons/*
  - libs/addons/**/*
