import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

// Autogenerated from the learn/ folder tree (see apps/docs/CONTRIBUTING.md).
const sidebars: SidebarsConfig = {
  learnSidebar: [{ type: 'autogenerated', dirName: '.' }],
}

export default sidebars
