import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

// The API reference sidebar is autogenerated from the api/ folder tree; order
// and labels come from each folder's _category_.json and per-file
// sidebar_position. See apps/docs/CONTRIBUTING.md.
const sidebars: SidebarsConfig = {
  apiSidebar: [{ type: 'autogenerated', dirName: '.' }],
}

export default sidebars
